POST http://localhost:8080/matches/create
Content-Type: application/json

{
  "tournament": { "id": 1 },
  "player1": { "id": 1 },
  "player2": { "id": 2 },
  "referee": { "id": 3 },
  "score": "",
  "completed": false
}
