# curl -X POST http://localhost:8080/users/search 
#     -H "Content-Type: application/json" 
#     -d '{"hasIncompleteMatch":true}'
POST http://localhost:8080/users/search
Content-Type: application/json

{
  "hasIncompleteMatch": true
}

###

